### ISSUE TITLE
Talk 4.2.2 GraphQl error with TALK_PLUGINS_JSON 

### ISSUE THREAD

**Issue by acheraime** [coralproject/talk#1414]
I'm about to register a few plugins on 4.2.2. The client page will keep spinning with a GraphQL error even with an empty object passed to TALK_PLUGINS_JSON.
Here's a snippet of my docker-compose.yml
```
version: '2'
services:
  talk:
    image: coralproject/talk:4.2.2
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - redis
    environment:
      #- NODE_ENV=development # remove this line in production
      - TALK_MONGO_URL=mongodb://mongo/talk
      - TALK_REDIS_URL=redis://redis
      - TALK_ROOT_URL=http://<ip_server>:3000
      - TALK_PORT=3000
      - TALK_JWT_SECRET=password
      - TALK_FACEBOOK_APP_ID=12345
      - TALK_FACEBOOK_APP_SECRET=123abc
      - TALK_SMTP_FROM_ADDRESS="ABC Company"<email_address@abc.com>
      - TALK_SMTP_HOST=<smtp_Server>
      - TALK_SMTP_PASSWORD=<smpt_password>
      - TALK_SMTP_PORT=587
      - TALK_SMTP_USERNAME=<username>
      - TALK_PLUGINS_JSON={"client":["talk-plugin-like"]}

  mongo:
    image: mongo:latest
    restart: always
    volumes:
      - mongo:/data/db
  redis:
    image: redis:latest
    restart: always
    volumes:
      - redis:/data
volumes:
  mongo:
    external: false
  redis:
    external: false
```

**Comment by kgardnr** [comment]
Hey @acheraime! Thanks for writing in. Can you share what your `plugins.json` file looks like?

**Comment by acheraime** [comment]
@kgardnr Thanks for your quick reply. See my plugins.json in attachment.
[plugins.js.txt](https://github.com/coralproject/talk/files/1776405/plugins.js.txt)
mybad! I don't have a plugins.json. My plugins are register via the TALK_PLUGINS_JSON env variable in my docker-compose.yml file.

**Comment by kgardnr** [comment]
Oh great, thanks for sharing that with me. 

Since you're using custom plugins, you'll need to go the Onbuild route, documented here: https://coralproject.github.io/talk/installation-from-docker/#onbuild

I'll explain the steps below for you.

Within the directory you have talk, create a new folder called `talk`. In that folder created a `plugins.json` that looks like this:

```
{
  "client": [
    "talk-plugin-like"
  ]
}
```

You'll also need a Dockerfile with just this line:

`FROM coralproject/talk:latest-onbuild`

And then add the `build` part to your docker-compose to look like this:

```
version: '2'
services:
  talk:
    build:
      context: ./talk
    restart: always
    ports:
      - "3000:3000"
```

Let us know if you have more questions!
