### ISSUE TITLE
Error: only one instance of babel-polyfill is allowed

### ISSUE THREAD

**Issue by smontlouis** [coralproject/talk#1729]
#### Intended outcome:
Everything should work fine.

#### Actual outcome:
`Error: only one instance of babel-polyfill` is allowed in embed.js

#### How to reproduce the issue:
In my react app:
```
  componentDidMount () {
    let d = document.createElement('script'); 
    d.type = 'text/javascript'; 
    d.async = true;
    d.src = 'http://127.0.0.1:3002/static/embed.js';
    d.onload = "Coral.Talk.render(document.getElementById('coral_talk_stream'), { talk: 'http://127.0.0.1:3002/'});";
    (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(d);

  }

```
In my docker-compose.yml I have:
```
    environment:
      - NODE_ENV=development # remove this line in production
      - TALK_MONGO_URL=mongodb://mongo/talk
      - TALK_REDIS_URL=redis://redis
      - TALK_ROOT_URL=http://127.0.0.1:3002
      - TALK_PORT=3002
      - TALK_JWT_SECRET=password
      - TALK_DISABLE_EMBED_POLYFILL=TRUE
```

In doubt I've done this too:
`docker build -t my-awesome-talk-image --build-arg TALK_WHITELISTED_LANGUAGES=fr --build-arg TALK_DISABLE_EMBED_POLYFILL=TRUE .`

**Comment by hminaeeBrunswicknews** [comment]
Why dont you import your coral code like this:

`import {Coral} from '../../../../common-widget/Coral';`


then:

`
    componentDidMount() {

        Coral.Talk.render(document.getElementById("your id"), {
            talk: 'talk url:3000/'
        });
    }`

**Comment by smontlouis** [comment]
Yeah good catch 😄!

But I'm still having the same issue.

I've done this : 
In my HTML.js:
`<script async src="http://127.0.0.1:3000/static/embed.js" />`

In my Component:
```
import React from 'react'
import { Component } from 'components'

export default class Comments extends Component {
  componentDidMount () {
    window.Coral.Talk.render(document.getElementById('coral_talk_stream'), { talk: 'http://127.0.0.1:3000/'});
  }
  render () {
    return (
      <div id="coral_talk_stream"></div>
    )
  }
}
```

**Comment by smontlouis** [comment]
![image](https://user-images.githubusercontent.com/3509412/42287046-2535278c-7fb5-11e8-9511-e00fbee9d240.png)

Disabling my local babel-polyfill, now I have this error :/

**Comment by hminaeeBrunswicknews** [comment]
So I think you do not need this anymore in your html:

`<script async src="http://127.0.0.1:3000/static/embed.js" />`

if you import it like this:

`import {Coral} from '../../../../common-widget/Coral';`

Create a file in a folder and import it as above and let me know if that fixed your issue

**Comment by wyattjoh** [comment]
Instead of mounting the component as the widget, we still recommend using the dynamic binding method, as it's best supported at the moment.

If you want to prevent duplicate polyfills from causing errors, refer to the [TALK_DISABLE_EMBED_POLYFILL](https://docs.coralproject.net/talk/advanced-configuration/#talk-disable-embed-polyfill) variable that you can use to prevent the polyfill from being injected into the embed.

**Comment by smontlouis** [comment]
@wyattjoh in my docker-compose.yml, I have the following:

```
# For details on the syntax of docker-compose.yml files, check out:
# https://docs.docker.com/compose/compose-file/compose-file-v2/

version: '2'
services:
  talk:
    image: my-awesome-talk-image:latest
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - redis
    environment:
      - NODE_ENV=development # remove this line in production
      - TALK_MONGO_URL=mongodb://mongo/talk
      - TALK_REDIS_URL=redis://redis
      - TALK_ROOT_URL=http://127.0.0.1:3000
      - TALK_PORT=3000
      - TALK_JWT_SECRET=password
      - TALK_DISABLE_EMBED_POLYFILL=TRUE

  mongo:
    image: mongo:latest
    restart: always
    volumes:
      - mongo:/data/db
  redis:
    image: redis:latest
    restart: always
    volumes:
      - redis:/data
volumes:
  mongo:
    external: false
  redis:
    external: false
```


But still got that error
