### ISSUE TITLE
Docker: Enabling/disabling plugins

### ISSUE THREAD

**Issue by freder** [coralproject/talk#1950]
I suppose this is related to #1881 and #1942

I wrote a custom `Dockerfile` to be able to serve static files from the same container, and to enable/disable plugins:

```
# https://docs.coralproject.net/talk/installation-from-docker/#onbuild
FROM coralproject/talk:4.6-onbuild

RUN apk add --update supervisor && rm -rf /tmp/* /var/cache/apk/*

WORKDIR /usr/src/app
RUN npm i -g serve

ADD supervisord.conf /etc/

ENTRYPOINT ["supervisord", "--nodaemon", "--configuration", "/etc/supervisord.conf"]
```

`docker-compose.yml`:

```yml
# [...]
services:
  talk:
    build: ./talk-docker-customized
    # [...]
    volumes:
      - ./static:/usr/src/static
      - ./plugins.json:/usr/src/app/plugins.json
# [...]
```

I started off by copying `plugins.default.json` to `plugins.json` and removing those plugins I don't need: for instance `talk-plugin-respect` and `talk-plugin-sort-most-respected`. but even after `docker-compose build && docker-compose up` the "respect" button still shows up in the UI.

not sure what I'm doing wrong.
