### ISSUE TITLE
[Question] How to remove the "My Profile" Tab

### ISSUE THREAD

**Issue by deepaksisodiya** [coralproject/talk#1962]
#### Do you want to request a **feature** or report a **bug**?

Question

#### Intended outcome:

I see in file **Embed.js**. We are adding the **my profile** tab if the current user in prop.
I do not want to modify the Talk code and still want to remove **my profile** tab
Is there any recommended way to achieve this?

<img width="438" alt="screen shot 2018-10-04 at 1 20 19 pm" src="https://user-images.githubusercontent.com/3258231/46460360-56a0a780-c7d9-11e8-80c3-b3d0b04f5b7b.png">

#### Version and environment

4.6.3

**Comment by wyattjoh** [comment]
You can add a custom css rule for it!

```css
.talk-tab-bar { display: none; }
```

Which should hide that whole bar.

If you only want to hide the "My profile" tab, you can remove it with:

```css
.talk-embed-stream-profile-tab { display: none; }
```
