### ISSUE TITLE
Error in JavaScript for the bundle.

### ISSUE THREAD

**Issue by voodooattack** [coralproject/talk#1973]
#### Do you want to request a **feature** or report a **bug**?
Report a bug.

#### Intended outcome:

Run the *-on-build image.

#### Actual outcome:

I get this error in my console when I try to load the iframe: 
```
Uncaught (in promise) TypeError: Cannot read property 'fields' of undefined
    at o (bundle.1bea1667b3d6f0d2d758.js:25)
    at bundle.1bea1667b3d6f0d2d758.js:25
    at u (bundle.1bea1667b3d6f0d2d758.js:25)
    at bundle.1bea1667b3d6f0d2d758.js:25
    at Array.reduce (<anonymous>)
    at i (bundle.1bea1667b3d6f0d2d758.js:25)
    at u (bundle.1bea1667b3d6f0d2d758.js:25)
    at bundle.1bea1667b3d6f0d2d758.js:25
    at Array.reduce (<anonymous>)
    at i (bundle.1bea1667b3d6f0d2d758.js:25)
```

#### How to reproduce the issue:

This is my current setup:

docker-compose.yml:
```
version: '2'
services:
  talk:
    build:
       context: ./build
#    image: coralproject/talk:latest
    dns:
      - 1.1.1.1
      - 1.0.0.1
      - 8.8.8.8
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - redis
    environment:
      - TALK_MONGO_URL=mongodb://mongo/talk
      - TALK_REDIS_URL=redis://redis
      - TALK_INSTALL_LOCK=TRUE
      - TALK_ROOT_URL=https://talk.themagineer.com/
      - TALK_PORT=3000
      - TALK_JWT_SECRET=******
      - TALK_GOOGLE_CLIENT_ID=****
      - TALK_GOOGLE_CLIENT_SECRET=****
  mongo:
    image: mongo:latest
    restart: always
    volumes:
      - mongo:/data/db
  redis:
    image: redis:latest
    restart: always
    volumes:
      - redis:/data
volumes:
  mongo:
    external: false
  redis:
    external: false
```

build/Dockerfile:
```
FROM coralproject/talk:latest-onbuild

ONBUILD RUN cli plugins reconcile && yarn && yarn build && yarn cache clean
```

build/plugins.json:
```
{
  "server":[
    "talk-plugin-featured-comments",
    "talk-plugin-local-auth",
    "talk-plugin-profile-data",
    "talk-plugin-respect",
    "talk-plugin-google-auth"
  ],
  "client":[
    "talk-plugin-auth",
    "talk-plugin-author-menu",
    "talk-plugin-featured-comments",
    "talk-plugin-flag-details",
    "talk-plugin-ignore-user",
    "talk-plugin-local-auth",
    "talk-plugin-member-since",
    "talk-plugin-moderation-actions",
    "talk-plugin-permalink",
    "talk-plugin-profile-data",
    "talk-plugin-respect",
    "talk-plugin-like",
    "talk-plugin-sort-most-replied",
    "talk-plugin-sort-most-respected",
    "talk-plugin-sort-newest",
    "talk-plugin-sort-oldest",
    "talk-plugin-viewing-options",
    "talk-plugin-google-auth"
  ]
}
```

As you can see, I'm using the default plugins and only adding 'google-auth'. The original image works flawlessly, but when I try to add the plugin that error happens in the browser.

#### Version and environment

Talk version: 4.6.4-onbuild
System: Ubuntu 18.04.1 LTS
Browser: Chrome Version 69.0.3497.100 (Official Build) (64-bit)
