### ISSUE TITLE
TENANT_NOT_FOUND error on Docker

### ISSUE THREAD

**Issue by flosoft** [coralproject/talk#2806]
Launching Talk via Docker Compose is failing on version 5.4.0 and above, including on a fresh deploy with the error: TENANT_NOT_FOUND and continuous redirects when trying to access it through nginx.
The configs are unchanged since 5.3.2, where this worked fine.

**Expected behavior:**
Instance should launch and show the setup page.

**Actual behavior:**
talk_1   | {"name":"coral","clusterNode":"master","hostname":"talk","pid":24,"level":50,"err":{"message":"TENANT_NOT_FOUND","name":"TenantNotFoundError","stack":"SubscriptionServer.onConnect (src/core/server/graph/subscriptions/server.ts:102:15)\nprocessTicksAndRejections (internal/process/task_queues.js:94:5)\n","id":"885a50f0-3b0f-11ea-a3e1-c9b2902f7387","context":{"pub":{"hostname":"docker-talk_talk_1"},"pvt":{}}},"msg":"could not setup websocket connection","time":"2020-01-19T23:00:48.639Z","src":{"file":"/usr/src/app/src/core/server/graph/subscriptions/server.ts","line":149,"func":"error"},"v":0}

**Versions:**
Docker 5.4.0 and above

**Config Files**
***docker-compose.yml***
```
version: "2"
services:
  talk:
    image: coralproject/talk:5.4.2
    restart: always
    hostname: talk
    #ports:
    #  - "127.0.0.1:3000:3000"
    depends_on:
      - mongo
      - redis
    environment:
      - MONGODB_URI=mongodb://mongo:27017/coral
      - REDIS_URI=redis://redis:6379
      - SIGNING_SECRET=<SECRET GOES HERE>
  mongo:
    image: mongo:latest
    restart: always
    volumes:
      - /home/ubuntu/configs/talk/data/mongo:/data/db
  redis:
    image: redis:latest
    restart: always
    volumes:
      - /home/ubuntu/configs/talk/data/redis:/data
networks:
  default:
    external:
      name: http
```

***nginx config on same docker network (http)***
```
server {
    listen       443 ssl http2;
    server_name  talk.domain.tld;

    location / {
        proxy_pass         http://docker-talk_talk_1;
        proxy_redirect     off;
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto https;
        proxy_set_header   X-Forwarded-Host $server_name;
        proxy_hide_header  X-powered-by;
    }
    location /api/v1/live {
        proxy_pass http://docker-talk_talk_1;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        #include /etc/nginx/proxy_params;
        #return 404;
        #access_log  off;
    }
    location /api/graphql/live {
        proxy_pass http://docker-talk_talk_1;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_buffering off;
        #include /etc/nginx/proxy_params;
        #return 404;
        #access_log  off;
    }
}
```
