### ISSUE TITLE
Remove user mail notifications block

### ISSUE THREAD

**Issue by alvarolg** [coralproject/talk#3307]
Hi, 
its possible remove the user mail notifications block in profile preferences? because I haven't enabled 'Email settings' in coral cofiguration but the preferences are showed in user profile. I have version 5 of Coral. 
Thanks!

**Comment by wyattjoh** [comment]
You can use CSS!

A custom css file with the following will hide it:

```css
.coral-emailNotifications {
  display: none;
}
```
