### ISSUE TITLE
TENANT_NOT_FOUND error on elastic bean stalk 

### ISSUE THREAD

**Issue by MuthomiMate** [coralproject/talk#3309]
I have deployed my coral talk instance on elastic beanstalk and I am using the lamda functions  to access the coral talk instance. I get an error when trying to create a story

**Expected behavior:**
It should create a story in the coral talk
**Actual behavior:**
```
    "response": {
        "error": {
            "id": "2503e5b1-3088-11eb-896f-df01b1702652",
            "code": "TENANT_NOT_FOUND",
            "type": "INVALID_REQUEST_ERROR",
            "message": "Tenant hostname (ef9if6p79i.execute-api.eu-west-1.amazonaws.com) not found."
        },
        "report": null,
        "status": 500
    },
    "request": {
        "query": "\n    mutation CreateStory {\n      createStory(input: {story: {id: \"dev_post_15\", url: \"https://dev.butterfly.sovtech.org/posts/15\", metadata: {title: \"dev_post_15\"}}, clientMutationId: \"\"}) {\n        story {\n          id\n        }\n      }\n    }\n  "
    }
}

    at GraphQLClient.<anonymous> (/var/task/node_modules/graphql-request/src/index.ts:72:13)
    at step (/var/task/node_modules/graphql-request/dist/src/index.js:40:23)
    at Object.next (/var/task/node_modules/graphql-request/dist/src/index.js:21:53)
    at fulfilled (/var/task/node_modules/graphql-request/dist/src/index.js:12:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  response: {
    error: {
      id: '2503e5b1-3088-11eb-896f-df01b1702652',
      code: 'TENANT_NOT_FOUND',
      type: 'INVALID_REQUEST_ERROR',
      message: 'Tenant hostname (ef9if6p79i.execute-api.eu-west-1.amazonaws.com) not found.'
    },
    report: null,
    status: 500
  },
  request: {
    query: '\n' +
      '    mutation CreateStory {\n' +
      '      createStory(input: {story: {id: "dev_post_15", url: "https://dev.butterfly.sovtech.org/posts/15", metadata: {title: "dev_post_15"}}, clientMutationId: ""}) {\n' +
      '        story {\n' +
      '          id\n' +
      '        }\n' +
      '      }\n' +
      '    }\n' +
      '  ',
    variables: undefined
  }
}
```
Here is my docker-compose file
```
version: '2'
services:
  talk:
    image: coralproject/talk:6
    restart: always
    ports:
      - "3000:5000"
    depends_on:
      - mongo
      - redis
    environment:
      - MONGODB_URI=mongodb://mongo/talk
      - REDIS_URI=redis://redis
      - SIGNING_SECRET=butterfly
      - TRUST_PROXY=uniquelocal
  mongo:
    image: mongo:latest
    restart: always
    volumes:
      - mongo:/data/db
  redis:
    image: redis:latest
    restart: always
    volumes:
      - redis:/data
volumes:
  mongo:
    external: false
  redis:
    external: false
```
