### ISSUE TITLE
docker v8 image not supported on Apple Silicon

### ISSUE THREAD

**Issue by elgreg** [coralproject/talk#4336]
**Expected behavior:**

Locally, I should be able to run a `docker compose up` with `image: coralproject/talk:8` on an apple silicon laptop.

**Actual behavior:**

I get an error `no matching manifest for linux/arm64/v8 in the manifest list entries`

This is resolvable by adding `platform: linux/amd64` to the docker-compose file, but is it possible that arm architecture could be added when pushing images to docker hub? Or does the stack actually need to run on amd64 and maybe docs should be updated with the platform line?

Here's the full *working* docker-compose file:

```yaml
version: "2"
services:
  talk:
    # Added to avoid error about no matching manifest for linux/arm64/v8 in the manifest list entries
    platform: linux/amd64
    image: coralproject/talk:8.5.0
    ports:
      - "127.0.0.1:5000:5000"
    depends_on:
      - mongo
      - redis
    environment:
      - MONGODB_URI=mongodb://mongo:27017/coral
      - REDIS_URI=redis://redis:6379
      - SIGNING_SECRET=[redacted]
  mongo:
    image: mongo:4.2
    volumes:
      - ./data/mongo:/data/db
  redis:
    image: redis:3.2
    volumes:
      - ./data/redis:/data
```
