### ISSUE TITLE
Callback URLs are not HTTPS

### ISSUE THREAD

**Issue by atsbob** [coralproject/talk#4699]
Hello team, I spun up a simple DO Droplet, and first configured the server to use HTTPS with a LetsEncrypt certificate. Added the appropriate proxy redirects in NGINX so that everything points to HTTPS URLs and that my Coral installation points to my text subdomain (e.g. https://talk.samplesite.com) 

I installed Coral and it looks like it's working fine via HTTPS but I noticed my callbacks are outputting HTTP URLs instead even though the Coral admin is loading of the secure protocol. In this case I was trialing Google but it's the same for all the callbacks, and the apps reject the request I guess because the callback URL protocol differs. Google won't accept an HTTP URL so I need to sort it out on the Coral side of things.

I even tried setting up SSL via caddy on a different instance just to cover my bases but still I get the same issue.

I guess a simple solution might be setting up an SSO but that's a last resort since I previously did not have a user base and would have preferred to just manage everything via Coral. 

![image](https://github.com/user-attachments/assets/d008b3e1-12e3-4b0c-ad05-706114804e9a)
![image](https://github.com/user-attachments/assets/58ad00eb-09fd-48c3-9182-15d2e49a7fe7)

Here is my Compose file

```
services:
  talk:
    platform: linux/amd64
    image: coralproject/talk:9.5.3
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mongo
      - redis
    environment:
      - MONGODB_URI=mongodb://mongo:27017/coral
      - REDIS_URI=redis://redis:6379
      - SIGNING_SECRET=${SIGNING_SECRET}
  mongo:
    image: mongo:latest
    volumes:
      - ./data/mongo:/data/db
  redis:
    image: redis:latest
    volumes:
      - ./data/redis:/data
```

And basic NGINX config

```
server {
    listen 80;
    server_name talk.site.com;
    
    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name talk.site.com;

    ssl_certificate /etc/letsencrypt/live/talk.site.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/talk.site.com/privkey.pem;

    location / {
        proxy_pass http://127.0.0.1:5000;  # Forward traffic to the Talk container on port 5000
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
```

Coral: 9.5.3
MongoDB: 8.0.3
Redis: 7.4.1
