### ISSUE TITLE
Incorrect url in "embed content stream" code after fresh installation

### ISSUE THREAD

**Issue by kenota** [coralproject/talk#960]
### Expected behavior
There should be correct url for `embed.js` script in  "embed comment stream" field after default installation.
### Actual behavior
Second slash / is missing in url for script load. For example, in my case, instead of 
`<script src="https://talk-coral.binarybuffer.com/embed.js" async onload="` 
I got code 
`<script src="https:/talk-coral.binarybuffer.com/embed.js" async onload="`
### Steps to reproduce behavior
Given this docker-compose.yaml
```
version: '2'
services:
  talk:
    image: coralproject/talk:3.4.0
    restart: always
    ports:
      - "127.0.0.1:5000:5000"
    depends_on:
      - mongo
      - redis
    environment:
      - TALK_MONGO_URL=mongodb://mongo/talk
      - TALK_REDIS_URL=redis://redis
      - TALK_ROOT_URL=https://talk-coral.binarybuffer.com
      - TALK_JWT_SECRET=14iswearitisrandom
      - TALK_FACEBOOK_APP_ID=123
      - TALK_FACEBOOK_APP_SECRET=test
  mongo:
    image: mongo:3.2
    restart: always
    volumes:
      - mongo:/data/db
  redis:
    image: redis:3.2
    restart: always
    volumes:
      - redis:/data
volumes:
  mongo:
    external: false
  redis:
    external: false
```
Run `docker-compose up -d`, then login go `admin/install` and finish installation. After installation, navigate to Configure->Tech Settings and observe the issue in "Embed content stream" section.
